# Generated by Django 5.2.9 on 2025-12-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前，相同数字按创建时间排序', verbose_name='显示顺序'),
        ),
    ]
