# Generated by Django 5.2.9 on 2025-12-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='订单创建时使用的单价（根据阶梯价格计算）', max_digits=10, null=True, verbose_name='成交单价'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='此档位的最小购买数量（包含）', verbose_name='最小数量')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='此档位的最大购买数量（包含），留空表示无上限', null=True, verbose_name='最大数量')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='此数量区间的单价', max_digits=10, verbose_name='单价')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '价格阶梯',
                'verbose_name_plural': '价格阶梯',
                'ordering': ['product', 'display_order', 'min_quantity'],
                'indexes': [models.Index(fields=['product', 'min_quantity', 'max_quantity'], name='shop_pricet_product_e1e19b_idx')],
            },
        ),
    ]
